title: ""
author: ""
description: ""

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: true          # show article previews on the home page instead of headlines
hide_navigation: false       # recommended if you have no pages and show_excerpts disabled
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# View settings
dark_theme: false            # enables dark mode
dark_header: false           # uses dark header whether dark_theme is enabled or not
minimal_theme: false         # radically minimalistic theme

#icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
#  envelope: ""
#  github: ""
#  feed: ""

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
